### ISSUE TITLE
Main Chat

### ISSUE THREAD

**Issue by remotevase** [Sites4Code/MCPE#2]
Instead of using the old PR, lets use this (@Taki21 @Keithkfng @Ad5001)

**Comment by k3ithos** [comment]
When was this org created...

**Comment by remotevase** [comment]
Yesterday (Or day before cant remember)

**Comment by remotevase** [comment]
EDIT: 6 days ago, was inactive until saturday, inactive yesterday, back today

**Comment by k3ithos** [comment]
Right.

**Comment by Ad5001** [comment]
Will start making the interface clearer I think...

**Comment by Ad5001** [comment]
Well change all the lessons by courses. Working on a saving system, a percent progress calculating system and finally, some exercises.

**Comment by Ad5001** [comment]
After thinking, maybe the saving course would be to hard due to the fact that we would need to use cookies so prevent the client, making terms and conditions...

**Comment by remotevase** [comment]
Yeah...

**Comment by Ad5001** [comment]
Btw I think we should redesign a bit the website to see the lessons first

**Comment by remotevase** [comment]
What do you mean?

**Comment by Ad5001** [comment]
The main website:
We might need to redesign it a bit to delete what's not necessery for the website and make it more organised as Courses and the nav should be for the courses.

**Comment by Taki21** [comment]
May i redesign? It's my turn to recontribute again :) ☺

**Comment by Ad5001** [comment]
I mean the main website (http://learn-mc.ga) the MCPE style is perfect :)

**Comment by remotevase** [comment]
@Ad5001 Yes, perfect but why is there blue box around tutorials?

**Comment by remotevase** [comment]
@Taki21 Ask @Ad5001

**Comment by Ad5001** [comment]
I think it looks more ordered. But maybe this blue is not the right color. Maybe some gray?

**Comment by remotevase** [comment]
maybe simply a tiny gap in between the tutorials (Like an invisible 4px white box)

**Comment by Ad5001** [comment]
we could use a css margin if I'm not mistaking

**Comment by remotevase** [comment]
Why not? I just think boxes are easier

**Comment by Ad5001** [comment]
If we set a margin to boxes, it will be 1 css line and it will be all done ;)

**Comment by remotevase** [comment]
Okay
